# Important: Use "flutter packages get", not "pub get".
name: flutter_built_redux
author: David Marne <davemarne@gmail.com>
version: 0.6.0
description: Built_redux provider for Flutter
homepage: https://github.com/davidmarne/flutter_built_redux
dependencies:
  flutter:
    sdk: flutter
  built_redux:
    git:
      url: https://github.com/miDeb/built_redux.git
      ref: nnbd
  meta: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  built_value: ^8.0.0-nullsafety.0
  built_value_generator: ^8.0.0-nullsafety.0
environment:
  sdk: '>=2.12.0-0 <3.0.0'
